server:
  port: 8082
  servlet:
    session:
      timeout: 1800
      cookie:
        max-age: 86400
spring:
  aop:
    auto: true
  application:
    name: 1.0
  mvc:
    static-path-pattern: /**
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.1.94:5432/mydb?characterEncoding=utf8&useSSL=true
    username: admin
    password: password
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    username:
    password:
    protocol: smtp
    test-connection: false
  servlet:
    multipart:
      max-file-size: -1 
      max-request-size: -1
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
mybatis:
  type-aliases-package: org.cloud.point.web.domain
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml
app:
  logOperation: true
  security:
    basic:
      enabled: true
swagger:
  enable: true
springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /api/swagger-ui.html
file:
  upload-dir: ./uploads
token:
  expire:
    seconds: 7200
  jwtSecret: (XIAO:)_$^11244^%$_(WEI:)_@@++--(LAO:)_++++_.sds_(SHI:)